# Generated by Django 4.0.4 on 2022-05-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgroComercio',
            new_name='AgroComercios',
        ),
        migrations.RenameModel(
            old_name='Productor',
            new_name='AsesoresTecnicos',
        ),
        migrations.RenameModel(
            old_name='AsesorTecnico',
            new_name='Productores',
        ),
    ]
